<!-- Slider -->
		<div class="subbanner">
		<img src="<?php echo base_url();?>images/banner1.png" class="img-responsive">
	</div>
	<!-- //Banner-Slider-JavaScript -->
	<!-- //Header -->

<!-- trend -->
<div class="disclaim">
<div class="container">
<div class="col-md-12">
<h2 class="text-center">Terms & Conditions </h2>
                <h4 style="text-align:left; margin-bottom:10px; margin-top:20px; color:#333;">AFFILIATE / DIRECT SELLER AGREEMENT / CONTRACT</h4>
               <p class="text-left">  Auras Way Private Limited, a Company incorporated under companies act 1956 Govt. of India. Auras Way was started in August 2018 with just 2 products and now we have a range of Product with us, (hereinafter referred to as the company) is engaged in the business of selling/marketing the products either manufactured by itself under its own trademark / logo or manufactured by the renowned companies under trademark / logo of the company and also of the renowned and branded companies under the agreement as a Licensee of their respective trademark which are displayed on its website www.aurasway.com through online and offline on or below the MRP as mentioned therein. WHEREAS the DIRECT SELLER who is already participating or intend to participate in a future in the direct selling network of the company for purchase/recommendation of the products mentioned thereof or the prospective buyer / direct seller / customer further intends to do the business activities of selling the products of the company, hereby agreed to do the same on the following terms and conditions which are to be complied by the existing as well as proposed Direct Seller:</p>
                <div class="single-news-text" style="margin-top:0px;">
                    <h4 style="text-align:left; margin-bottom:10px; margin-top:20px; color:#333;">NOW THIS AGREEMENT WITNESSETH AS UNDER</h4>
                    <ul style="margin-top:0px;">
                        <li><i class="fa fa-hand-o-right"></i>  The Affiliate/Direct seller and the company shall undertake to comply the guidelines issued vide F. No. 21/18/2014-IT (Vol-II) dated 9th September, 2016 by Department of Consumer Affairs (Ministry of Consumer Affairs, Food and Public Distribution, GOI) as DIRECT SELLING GUIDELINES, 2016 and notified as G.S.R. 1013(E) dated 26th October 2016 with its true spirit and object. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The Affiliate/Direct Seller hereby confirms that he / she has entered into this agreement as an Direct seller and nothing in this agreement shall establish an employment relationship, or any other labour relationship or agent etc. between the Direct Seller and the company and nothing shall establish the Affiliate /Direct Seller position as Procurer, broker, commercial agent or other representative of the company.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The Affiliate /direct seller understands that he/she is working as an direct seller only operating the company business and shall neither convey the impression or refer himself/herself as employee, agent, manager, or representative of company nor use such terminology and shall hereby undertake to indemnify the company in respect of any costs or damages arising as a result of any such malafide  representation of relationship with company. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The company shall not impose a condition on a AFFILIATE/direct seller that they will receive remuneration or incentives ONLY on recruitment / enrolment of new participants/ subscribers; and shall not require a participant/ subscriber to purchase goods or services for an amount or quantity that exceeds expected sale, consumption, resale of goods or sale of services to the consumers within a stipulated time. And further it does not require a participant/ subscriber to pay any entry/registration fee, cost of demonstration equipments and materials or other fees relating to participation;</li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct Seller shall be entitled for only remuneration which is to be paid as per the sale of the goods/products by them and the information about the applicable taxes including VAT or other taxes existing under the law have already been apprised to them and the same have been understood and acknowledged by them.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller shall not indulge in any misleading, deceptive or unfair trade practice or making false, deceptive or unfair means to recruit prospective direct sellers. The company shall be at liberty to terminate the agreement with the affiliate/direct seller without any notice and the said direct seller shall be personal liable for the consequences thereof in the eyes of law, in case of any false representation, omission or any act committed by them, contrary to the guidelines issued by the Govt. of India as mentioned hereinabove or the Code of Conduct, independent advisor agreement, legal agreement, affidavit and important notice as depicted in the website of the company Affari Networks. Apart from that the company, further shall be at liberty to terminate the contract in a situation where a direct seller is found to have made no sales of goods for a period of 2 years since the day of inception of contract or since the day of last sale made by him or anything wrongly / falsely made by the AFFILIATE/direct seller to the prospect / customer to sell the product contrary to the norms of the company.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller undertakes and are becoming the part of the business activities of the company on their own volition without any pressure, duress or undue influence and voluntarily electing to promote and promulgate the sales of the products offered by the company, fully understanding that it is an offered based venture, and only augment of product sells and successful marketing of the products offered by company, would fetch, remunerations and there being no automatic remunerations scheme or investment plan and the company does not indulge in any kind of financial investment or float any investment scheme or entrepreneurship or money circulation scheme.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The company shall be responsible for redressal of the grievances of the consumers as may be arising on account of Direct Selling Activities conducted by the Direct Sellers and a grievance redressal committee having four members including nodal officer/chairman with their respective addresses, phone no. etc. has already been constituted, showing the same on the website of the company and whatever complaint which is received either on our landline phone, mobile, email, website, posts or personally visits by the aggrieved person shall be given a complaint No. for tracking the status of the complaints and also to assess the time taken for redressal of the complaint.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The present agreement is being executed by the AFFILIATE/Direct Seller without any compulsion, inducement made by the company and the company has not compelled the Direct Seller to purchases the goods / products in an amount that exceeds an amount that can be expected to be sold to the consumers within reasonable period of time and further allow the direct seller a reasonable cooling off period of 30 days which entitles such AFFILIATE/Direct seller to return the product / goods purchased by him / her during the said cooling off period subject to return of goods / products having without any damage or alteration to the goods / product in a question as marketable value. Besides that the company shall further allows or provides for a participant a buy-back policy for “currently marketable” goods / products sold to the participant at the request of the participant within period of 30 days from the date of distribution of goods / products at reasonable terms;</li>
                        <li><i class="fa fa-hand-o-right"></i>  It makes clear that neither the AFFILIATE/Direct seller nor the company shall take any entry/registration fee, cost of sales demonstration equipment and materials or other fees relating to participation from the participant and further shall provide a written contract describing the “material terms” of participation to the participant;</li>
                        <li><i class="fa fa-hand-o-right"></i>  It is understood and made clear in unequivocal words that the company or the AFFILIATE/Direct seller do not participate in any money circulation scheme or promote / engaged in a pyramid scheme and company / AFFILIATE / Direct seller shall not require from a participant to pay any entry / registration fee, cost of sales, demonstrations equipment’s and material or other fees relating to participation.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller shall not make any incentives / remuneration to the prospective customer for the recruitment / enrolment, except from the sale of goods / products and the direct seller shall not be entitled to get any money by way of minimum monthly subscription or renewal charges from the prospective customer etc.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller shall not sell any products for a price exceeding the MRP and this agreement becomes effective from the date of acceptance by the company. The identification card issued to the Direct Seller is and shall remain the property of the company and the Direct Seller shall return the same to the Company without any delay upon terminate or expiration of this agreement. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The company may reject the instant agreement for any reason, at its discretion, including if the Direct Seller furnish incomplete, inaccurate, false or misleading information at the time of entering into this agreement. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller undertakes that they shall not provide any literature or training material not restricted to collateral issues by the direct selling entity to prospective or existing direct seller which has not been approved by direct selling entity or require prospective or existing direct seller to purchase any literature or training material or sales demonstration equipment’s. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller shall endeavour to always treat others well and has already attained age of maturity at the time of entering into this agreement besides has executed an affidavit in that respect as displayed on the website of the company. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller shall represent company products/services and its Sales and Marketing Plan to all prospective users/customers in a truthful and honest manner, and he/she will make sure to represent only what is approved in official company publications and on its website. Further the affiliate/direct seller shall conduct themselves in such a manner as to reflect only the highest standards of honesty, integrity and responsibility because he/she recognizes that his/her conduct as direct seller has far-reaching effects. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller shall not sell / market the products of other companies except the company mentioned hereinabove and its published material authorized by the company. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller shall not while inviting a prospective customers/users directly or indirectly induce them during their meeting with impression that the invitation extended to them by he/she are for participation in some ‘social event’ or to disguise the invitation as market survey; or to imply that it is other than a business event; and shall not emphasize more on the potential earning trough the Marketing Plan of company than the utility of the products/services of the company; or represent that a person can benefit solely by referring to others or by obtaining products/services for personal use at his own costs; or claim that one may achieve success or benefit with little or no investment by way of effort or time. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller shall emphasize that income by way of commission / remuneration can be achieved only by way of continuous augment of product sells / activities and effort in that direction to the perspective user and shall not exaggerate or overstate the kind of potential earnings that can be generated by the company business and communicate. Only true and actual earnings shall be projected him/her; </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller undertakes to observe all laws, policy, rules and/or regulations, central or local as may be applicable from time to time and shall keep the company indemnified against all actions, claims, demands, prosecution, penalties including costs thereof and not excluding company legal costs which might be made or brought against the company in respect of any of or arising out of any breach, infringement or infraction of any laws, regulations and code of practice, by me, arising out of the operation of the company Business. </li>
                        <li><i class="fa fa-hand-o-right"></i>  <strong>Commission :</strong> A. Sole Compensation :The Company shall pay the Affiliate a commission at such rate as may be communicated by the Company in writing to the Affiliate, for whole or part of the goods/services hereto, based on the Maximum Retailing Price of the product as fixed by the company on every new order. This commission will be subjected to the relevant taxes as applicable. The Company reserves its right to revise the rate of commission from time to time and the same shall be intimated to the Affiliate in writing by the Company. B. Basis of Commission: The Commission shall apply to all sales orders from customers solicited by Affiliate. (Customers defined as an individual or a company who have bought the product/goods/services from the Affiliate for their own use.) No commissions shall be paid on (i) orders solicited directly by Company within the Territory; (ii) orders received from outside the Territory unless otherwise agreed in writing by Company. (iii) No commission will be paid to the Affiliate until 100% payment pertaining to the order is received. The company reserves the right to change the commission / prices on products as and when required.  C. Time of Payment : The commission on all PAID ORDERS shall be due and payable within thirty (30) working days after the Affiliate raises invoice.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller shall not engage in any activities, which may bring daffiliateepute to the company or any products/services of the company and undertake to indemnify the company on account of any costs or damages that may arise due to any such activities. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller shall comply with all requirements, guidelines, which are issued from time to time by the company or any competent authorities including the Govt. of India or the State Governments and any in disciplinary action performed by affiliate/direct seller, may result in termination. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller with his / her own volition, without any duress, coercion or undue influence agreed to opt for the marketing plan/work of the company and fully understand that it is an effort based plan where you, the Direct Seller achieve remuneration / commission only by way of continuous augment of product sells / activities and by effort based activity to refer/market/sell the products/services offered by the company, (there being no automatic rewards scheme or investment plan). </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller understands that if he/she ceases to be affiliate/direct seller for any reason, they will automatically lose all/any rights under this Agreement. And understood and are not under any illusion/wrong impression as to the kind of potential earnings that can be generated by the company business. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The AFFILIATE/Direct seller shall be responsible for complying with all laws, policies, rules or regulations, taxes, levies, central or local, as may be applicable from time to time and obtaining all licenses and/or registration as may be required from time to time. </li>
                        <li><i class="fa fa-hand-o-right"></i>  It is specifically pleased to be noted that in case the direct seller are employed by any central government/state government agency, Indian armed forces or any such establishment that disallows you to work part time/full time/earn remuneration/commissions, in that situation, you will not be able to enter into this agreement. </li>
                        <li><i class="fa fa-hand-o-right"></i>  The affiliate/direct seller accepts that it is the prerogative of the management of the company to alter, amend or reduce the amount of commission/remuneration to the independent advisor without prior notice. </li>
                        <li><i class="fa fa-hand-o-right"></i>  That the affiliate/direct seller also understood and read the contents of document under the heading of Legalities as available and displayed on the website of the company i.e. www.aurasway.com and undertake to abide all the stipulations as envisaged in the said Legal Document. </li>
                        <li><i class="fa fa-hand-o-right"></i>RETURN POLICY:</li>

                        <ul style="margin-left: 40px;">
                            <li><i class="fa fa-arrow-circle-o-right"></i>  In case Distributors has received any damaged product, he/she can exchange from where he/she has got the delivery of the same within 10 days of delivery.</li>
                            <li><i class="fa fa-arrow-circle-o-right"></i>  Distributor can return unsold products to the company within 30 days from the date of purchase with original invoice as per return policy of the company .Such products are must be into resalable condition.</li>

                        </ul>
                        <li><i class="fa fa-hand-o-right"></i>  COOLING OFF PERIOD :</li>

                        <ul style="margin-left: 40px;">
                            <li><i class="fa fa-arrow-circle-o-right"></i>  New distributor can surrender his /her business within 30 Days from the date of sign up under cooling off period. They can return unsold products to company with original invoice as per return policy of the company such products are must be into resalable condition.</li>


                        </ul>
                        <li><i class="fa fa-hand-o-right"></i>  For all purposes, only in English version of printed material from the company will be taken as an official copy.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The company is the Authority to interpret the rules, regulations instructions and sales policy applicable to and governing the conduct of the distributor.</li>
                        <li><i class="fa fa-hand-o-right"></i>  The company reserves the right to change, modify and alter the business plan, rules, regulations, prices, terms and conditions and code of ethics without any prior notice or intimation to the distributor.</li>
                        <li><i class="fa fa-hand-o-right"></i>  Any dispute, difference or claims arising out of as in connection with this agreement shall be submitted to arbitration and shall be referred to the sole arbitrator under the Arbitration and conciliation Act 1996 and its rules. The venue of such arbitration shall be at Firojpur shall be final and binding on all parties. The courts at Firojpur shall alone have jurisdiction in relation to this Arbitration Agreement and any award there from.</li>
                        <li><i class="fa fa-hand-o-right"></i>  Auras Way Private Limited is a Private limited company into the corporate under the Companies act of 2013, registered with the registrar of companies, Firojpur and having its head office at Firojpur. All disputes or differences shall be adjudicated upon by a court of an appropriate jurisdiction at Firojpur only.</li>
                        <li><i class="fa fa-hand-o-right"></i> This Agreement is made and executed at Firojpur on this _____ day of ____________ year _________ between Shri____________________________________ S/D/W/o Shri _____________________________________R/o__________________________________________________________________________ (AFFILIATE/DIRECT SELLER) AND M/s Auras Way Pvt. Ltd.</li>
                        <p class="text-left">(DIRECT SELLING ENTITY)</p>
                        <p class="text-left">Authorized Signatory	 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;		(AFFILIATE/DirectSeller) </p>
                        <p class="text-left">Signature	 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;	Signature</p>
                        <p class="text-left">Date  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;	ID No.</p>
                        <p class="text-left">Place</p>


                </ul></div>
            </div>
</div></div>

